name: Issues Output
on:
  issues:
    types: [opened]
jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print Output
              run: echo "${{toJson(github.event)}}"
