name: Lint Test Deploy
on: push
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Build
              run: npm run build
    lint:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Run Lint Script
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Run Tests
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Deploy
              run: echo "Deployed"
